version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Build started on `date`
      - echo npm install
  build:
    commands:
      - echo Entered the build phase...
  post_build:
    commands:
      - echo Entered the post build phase...
      - echo Build completed on `date`